version: '3.3'
services:
  root:
    image: 192.168.1.102:5000/front/root:0.0.1-SNAPSHOT
    volumes:
    - /home/logs/front:/logs
    networks:
    - front
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        #constraints: [node.labels.work == a]
        preferences:
        - spread: node.labels.work
  manage:
    image: 192.168.1.102:5000/front/manage:0.0.1-SNAPSHOT
    volumes:
    - /home/logs/front_manage:/logs
    networks:
    - front
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        #constraints: [node.labels.func == app]
        preferences:
        - spread: node.labels.work
  trade:
    image: 192.168.1.102:5000/front/trade:0.0.1-SNAPSHOT
    volumes:
    - /home/logs/trade:/logs
    networks:
    - front
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        #constraints: [node.labels.func == app]
        preferences:
        - spread: node.labels.work
  coin:
    image: 192.168.1.102:5000/front/coin:0.0.1-SNAPSHOT
    volumes:
    - /home/logs/coin:/logs
    networks:
    - front
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        #constraints: [node.labels.func == app]
        preferences:
        - spread: node.labels.work
networks:
  front:
    external: true