spring:
  redis:
    host: middleware_redis1
    port: 6379
    password: 123456
    pool:
      max-active: 20
      max-wait: 1
      max-idle: 5
      min-idle: 0
    timeout: 10000
  redis1:
    host: middleware_redis2
    port: 6379
    password: 123456
    pool:
      max-active: 20
      max-wait: 1
      max-idle: 5
      min-idle: 0
    timeout: 10000
  datasource:
    druid:
      filters: config,stat,wall
      connect-properties: config.file=http://47.75.200.109/druid-pool.properties
      driver-class-name: com.mysql.jdbc.Driver
      url:
      username:
      password:
      initial-size: 1
      min-idle: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  rabbitmq:
    host: middleware_rabbitmq
    port: 5672
    username: qq
    password: 1234
    virtual-host: /qq
server:
  port: 8087
  context-path: /exapi
zookeeper:
  url: zookeeper://middleware_zookeeper:2181
dubbo:
  name: tp-exapi
  port: 20904
  host: middleware_zookeeper
  cachepath: cache
logging:
  level: trace
  path: logback.xml