CREATE TABLE `otc_order_transaction` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `transactionNum` VARCHAR(100) COLLATE utf8_bin DEFAULT NULL COMMENT '委托订单号',
  `transactionOrderNum` VARCHAR(100) COLLATE utf8_bin DEFAULT NULL COMMENT '交易订单号',
  `userName` VARCHAR(100) COLLATE utf8_bin DEFAULT NULL COMMENT '用户登录名',
  `buyCustomId` BIGINT(20) NOT NULL COMMENT '买方的id',
  `sellCustomId` BIGINT(20) NOT NULL COMMENT '卖方的id',
  `buyAccountId` BIGINT(20)  NULL COMMENT '买方虚拟账户id',
  `sellAaccountId` BIGINT(20)  NULL COMMENT '卖方虚拟账户id',
  `transactionType` SMALLINT(2) DEFAULT NULL COMMENT '交易类型(1买,2卖)',
  `paymentType` VARCHAR(255) DEFAULT NULL COMMENT '付款类型(Alipay 支付宝,WeChat 微信，Bank 银行转账)',
  `paymentTime` DATETIME DEFAULT NULL COMMENT '付款时间',
   finishTime DATETIME DEFAULT NULL COMMENT '完成时间',
  `transactionMoney` DECIMAL(20,10) DEFAULT NULL COMMENT '交易金额',
  `transactionCount` DECIMAL(20,10) DEFAULT NULL COMMENT '交易数量',
  `transactionPrice` DECIMAL(20,10) DEFAULT NULL COMMENT '交易单价',
  `dealQuantity` DECIMAL(20,10) DEFAULT NULL COMMENT '成交量',
  `surplusQuantity` DECIMAL(20,10) DEFAULT NULL COMMENT '剩余量',
  `appealHandle` VARCHAR(255) COLLATE utf8_bin DEFAULT null COMMENT '申诉处理 Colse 关闭，Finish 完成，Refuse 拒绝',
  `appealCustomId` BIGINT(20) DEFAULT NULL COMMENT '申诉方的id',
  `appealCustomName` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL COMMENT '申诉方的名字',
  `appealFlag` VARCHAR(255) COLLATE utf8_bin DEFAULT 'N' COMMENT '申诉标识',
  `appealReason` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL COMMENT '申诉原因',
  `status` SMALLINT(2) DEFAULT NULL COMMENT '1未付款 2已付款 3已取消 4 已完成 5 已关闭,6 申诉中',
  `remark` VARCHAR(20) COLLATE utf8_bin DEFAULT NULL COMMENT '备注',
  `coinCode` VARCHAR(20) COLLATE utf8_bin DEFAULT '' COMMENT '币种',
  `fee` DECIMAL(20,10) DEFAULT '0.0000000000' COMMENT '手续费',
  `created` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `modified` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `createBy` BIGINT(20) NOT NULL COMMENT '创建人',
  `saasId` VARCHAR(255) COLLATE utf8_bin NOT NULL COMMENT 'saasId',
  `businessmanId` BIGINT(20)  NULL,
  `businessmanBankId` BIGINT(20)  NULL,
  `randomNum` VARCHAR(20) COLLATE utf8_bin DEFAULT '',
  `customerBankId` BIGINT(20) DEFAULT NULL,
  `transactionId` BIGINT(20) DEFAULT NULL,
  `status2` SMALLINT(2) DEFAULT NULL,
  `cancelFlag` VARCHAR(255) COLLATE utf8_bin  COMMENT '取消标识',
  `cancelBy` BIGINT(20)  COMMENT '取消人',
  `cancelDate` DATETIME DEFAULT NULL  COMMENT '取消日期',
  `img1` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
  `img2` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
  `img3` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
  `img4` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
  `img5` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
  `img6` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
  `businessman` VARCHAR(255) COLLATE utf8_bin DEFAULT NULL,
   attribute1  VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  attribute2  VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  attribute3  VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  attribute4  VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  attribute5  VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=219 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='otc交易订单表'